language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - jruby-19mode
  - rbx-19mode
gemfile:
  - Gemfile
  - gemfiles/Gemfile.base-versions
matrix:
  exclude:
    # Nokogiri 1.3.3 is not compatible with Rubinius or JRuby
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: rbx-19mode
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: jruby-19mode
  allow_failures:
    - gemfile: Gemfile
      rvm: rbx-19mode
    - gemfile: Gemfile
      rvm: jruby-19mode
    - gemfile: Gemfile
      rvm: ree
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: ree
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
