language: ruby
dist: trusty
sudo: required
rvm:
  - 2.0.0
  - 2.2
  - rbx-3.26
gemfile:
  - Gemfile
matrix:
  include:
    - gemfile: Gemfile
      rvm: 2.3.0
      env: WINDOW_TEST=true
    - gemfile: gemfiles/Gemfile.ruby-19
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.beta-versions
      rvm: 2.3.0
    - gemfile: Gemfile
      rvm: 2.2
      env: CAPYBARA_CHROME=true
  allow_failures:
    - gemfile: gemfiles/Gemfile.beta-versions
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - awesome

before_install:
  - if [ $CAPYBARA_CHROME ]; then
      CHROMEDRIVER_VERSION=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE);
      CHROMEDRIVER_URL="http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip";
      FILE=`mktemp`; wget "$CHROMEDRIVER_URL" -qO $FILE && unzip $FILE chromedriver -d ~; rm $FILE; chmod 777 ~/chromedriver;
    fi
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1
  - mkdir -p ~/.config/awesome
  - echo "require('awful'); tags = {}; tags[1] = awful.tag({'name'})" > ~/.config/awesome/rc.lua
  - "awesome &"
script: "bundle exec rake travis"
