language: ruby
sudo: required
notifications:
  webhooks: https://coveralls.io/webhook
services:
  - docker
  - xvfb
rvm:
  - 2.7
  - jruby-9.2.11.1
gemfile:
  - Gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom
    - WD_CACHE_TIME=0

addons:
  update: true
  chrome: stable
  apt:
    packages:
      - awesome

branches:
  except:
    - /^ie_/

cache:
  bundler: true
  directories:
    - ~/.webdrivers

matrix:
  include:
    - gemfile: gemfiles/Gemfile.gumbo
      rvm: 2.6
      script: bundle exec rake rack_smoke
    - gemfile: Gemfile
      rvm: 2.6
      env: CAPYBARA_REMOTE=true
    - gemfile: Gemfile
      rvm: 2.6
      env:
        - CAPYBARA_REMOTE=true
        - CAPYBARA_FF=true
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: 2.5
      env: CAPYBARA_FF=true
      addons:
        firefox: latest
        apt:
          packages:
            - awesome
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: 2.5
    - gemfile: Gemfile
      rvm: 2.6
      env: HEADLESS=true
    - gemfile: gemfiles/Gemfile.beta-versions
      rvm: 2.6
      env: CAPYBARA_FF=true
      addons:
        firefox: latest-beta
        apt:
          packages:
            - awesome
    - gemfile: gemfiles/Gemfile.edge-firefox
      rvm: ruby-head
      env:
        - CAPYBARA_FF=true
        - CAPYBARA_REMOTE=true
    - gemfile: Gemfile
      rvm: ruby-head
      env: RUBY_OPT=--jit
    - gemfile: Gemfile
      rvm: 2.7
      env: CAPYBARA_FF=true
      addons:
        firefox: latest
        apt:
          packages:
            - awesome
    - gemfile: Gemfile
      rvm: 2.5
      env: CAPYBARA_FF=true HEADLESS=true
      addons:
        firefox: latest
    - gemfile: Gemfile
      rvm: 2.6
      env: CHROME_BETA=true HEADLESS=true
      addons:
        update: true
        chrome: beta
    - gemfile: Gemfile
      os: osx
      osx_image: xcode10.2
      rvm: 2.6
      addons:
        homebrew:
          taps: homebrew/cask-versions
          casks: safari-technology-preview
      before_script:
        - "sudo /usr/bin/safaridriver --enable"
        - "sudo '/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver' --enable"
      script: "bundle exec rake spec_safari"
    - gemfile: gemfiles/Gemfile.chrome_edge
      os: osx
      osx_image: xcode10.2
      rvm: 2.6
      addons:
        homebrew:
          taps: homebrew/cask-versions
          casks: microsoft-edge-dev
      before_install:
        - wget https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/76.0.168.0/edgedriver_mac64.zip
        - unzip edgedriver_mac64.zip -d /usr/local/bin
      script: "bundle exec rake spec_edge"
  allow_failures:
    - os: osx
    - gemfile: gemfiles/Gemfile.beta-versions
    - gemfile: gemfiles/Gemfile.edge-firefox
    - env: CHROME_BETA=true HEADLESS=true
    - rvm: jruby-9.2.11.1
    - rvm: ruby-head
before_install:
  - gem update --system
  - if [[ $BUNDLE_GEMFILE =~ Gemfile.edge-firefox$ ]]; then
      pushd ..;
      git clone --depth 1 https://github.com/SeleniumHQ/selenium.git;
      cd selenium; ./go //rb:gem:build;
      popd;
      bundle config local.selenium-webdriver ../selenium/build/rb;
    fi
before_script:
  - if [[ -z $HEADLESS && -z $CAPYBARA_REMOTE ]]; then
      mkdir -p ~/.config/awesome;
      echo "require('awful'); tags = {}; tags[1] = awful.tag({'name'})" > ~/.config/awesome/rc.lua;
      awesome &
    fi
  - if [[ $CAPYBARA_REMOTE = true ]]; then
      if [[ $CAPYBARA_FF = true ]]; then
        docker-compose up -d selenium_firefox;
      else
        docker-compose up -d selenium_chrome;
      fi;
    fi

script: "bundle exec rake travis"
