language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-2.1.1
  - rbx-2.1.0
  - rbx-2.0.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile.base-versions
matrix:
  exclude:
    # Nokogiri 1.3.3 is not compatible with Rubinius or JRuby
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: rbx-2.1.1
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: rbx-2.1.0
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: rbx-2.0.0
    - gemfile: gemfiles/Gemfile.base-versions
      rvm: jruby-19mode
before_install:
  - URL='https://chromedriver.googlecode.com/files/chromedriver_linux32_26.0.1383.0.zip'; FILE=`mktemp`; wget "$URL" -qO $FILE && sudo unzip $FILE chromedriver -d /usr/local/bin; rm $FILE
  - URL='https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb'; FILE=`mktemp`; wget "$URL" -qO $FILE && sudo dpkg -i $FILE; rm $FILE
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
script: "bundle exec rake travis"
  
