version: 1.0.{build}-{branch}

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 25
      CAPYBARA_FF: true
    - RUBY_VERSION: 25
      CAPYBARA_IE: true
      BUNDLE_GEMFILE: gemfiles/Gemfile.ie
    - RUBY_VERSION: 23

matrix:
  allow_failures:
    - CAPYBARA_IE: true
    - CAPYBARA_EDGE: true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - cinst Firefox GoogleChrome
  # Registry hack so driver can maintain connection
  - REG ADD "HKLM\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BFCACHE" /v iexplore.exe /t REG_DWORD /d 00000000
  - REG ADD "HKLM\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BFCACHE" /v iexplore.exe /t REG_DWORD /d 00000000
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake travis