version: 1.0.{build}-{branch}

cache:
  - vendor/bundle

# image: Visual Studio 2017

environment:
  matrix:
    # - RUBY_VERSION: 25
    #   CAPYBARA_FF: true
    - RUBY_VERSION: 25
      CAPYBARA_IE: true
      BUNDLE_GEMFILE: gemfiles/Gemfile.ie
    # - RUBY_VERSION: 23

matrix:
  allow_failures:
    - CAPYBARA_IE: true
    - CAPYBARA_EDGE: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1600 1200
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - cinst Firefox GoogleChrome
  # Registry hack so driver can maintain connection
  - REG ADD "HKLM\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BFCACHE" /v iexplore.exe /t REG_DWORD /d 00000000
  - REG ADD "HKLM\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BFCACHE" /v iexplore.exe /t REG_DWORD /d 00000000
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  # - ps: Invoke-WebRequest 'https://github.com/SeleniumHQ/selenium/raw/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe' -OutFile 'C:\Tools\WebDriver\IEDriverServer.exe'
  - ruby -v
  - gem -v
  - bundle -v
  # - chromedriver.exe --version
  # - geckodriver.exe --version
  # - IEDriverServer.exe --version

test_script:
  - bundle exec rake travis