version: "3"
services:
  selenium_chrome:
    network_mode: "host"
    image: "selenium/${SELENIUM_IMAGE:-standalone-chrome}"
    volumes:
      - "/dev/shm:/dev/shm"
  selenium_firefox:
    network_mode: "host"
    image: "selenium/${SELENIUM_IMAGE:-standalone-firefox}"
    volumes:
      - "/dev/shm:/dev/shm"
    environment:
      - SE_OPTS=-port 4445
extra_hosts:
  - "host.docker.internal:host-gateway"
